version: "3.8"
services:
    api:
        container_name: deliverymap
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - "8080:3000"
            - "8081:9229"
        environment: 
            DATABASE_URL: postgres://user:password@postgres:5432/db
            NODE_ENV: development
            PORT: 3000
            PORT_API: 8080
        volumes:
            - "./:/app"
        links:
            - postgres

    postgres:
        container_name: postgres-database
        image: postgres:11.5-alpine
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        volumes:
            - ./db-data/:/var/lib/postgresql/data/
        ports:
            - "3333:5432"